compileWith:
	javac ConHebras.java
runWith:
	java ConHebras
compileWithout:
	javac SinHebras.java
runWithout:
	java SinHebras

startWith: compileWith runWith
startWithout: compileWithout runWithout

	

